# typed: false
# frozen_string_literal: true

# This file is generated by meetless-cli/homebrew/render-cask.sh on each release.
# Do not edit by hand; edits are overwritten on the next version bump.
cask "mla" do
  version "0.2.2"

  sha256 "fbc2e73245fc007588725235eed930967e25dbeb8c8407035ec37cad21f35561"

  url "https://storage.googleapis.com/meetless-public/cli/releases/download/v#{version}/mla-aarch64-apple-darwin.tar.gz"
  name "Meetless CLI"
  desc "Change-governance CLI (mla) for product delivery"
  homepage "https://meetless.ai"

  depends_on arch: :arm64

  binary "mla"

  caveats <<~CAVEATS
    The mla command is now on your PATH via Homebrew.
    Get started:  mla --help
  CAVEATS
end
