# typed: false
# frozen_string_literal: true

# This file is generated by meetless-cli/homebrew/render-cask.sh on each release.
# Do not edit by hand; edits are overwritten on the next version bump.
cask "mla" do
  version "0.2.36"

  sha256 "bd5a461a5799ac82228f70c77521f5bbfd6e29458cb92394cbb4ab66b1d64d6b"

  url "https://storage.googleapis.com/meetless-public/cli/releases/download/v#{version}/mla-aarch64-apple-darwin.tar.gz"
  name "Meetless CLI"
  desc "Change-governance CLI (mla) for product delivery"
  homepage "https://meetless.ai"

  depends_on arch: :arm64

  binary "mla"

  # The release binary is ad-hoc signed; Developer-ID notarization is not wired
  # yet. Homebrew stamps com.apple.quarantine on cask artifacts, and on Apple
  # Silicon a quarantined + un-notarized binary is SIGKILLed by Gatekeeper
  # (exit 137) with a scary "move to Trash" popup. Strip the quarantine xattr so
  # `mla` runs. This is the stopgap; delete it once the binary is notarized +
  # stapled (build-release.sh MLA_APPLE_* path), which fixes it at the source.
  postflight do
    system_command "/usr/bin/xattr",
                   args: ["-dr", "com.apple.quarantine", staged_path]
  end

  caveats <<~CAVEATS
    The mla command is now on your PATH via Homebrew.
    Get started:  mla --help
  CAVEATS
end
