# typed: false
# frozen_string_literal: true

# This file is generated by meetless-cli/homebrew/render-cask.sh on each release.
# Do not edit by hand; edits are overwritten on the next version bump.
cask "mla" do
  version "0.2.0"

  sha256 "cd82d616b25333ce149c966a7d6db13b733a3a43d36b58004a9a69b6edc9a7e7"

  url "https://storage.googleapis.com/meetless-public/cli/releases/download/v#{version}/mla-aarch64-apple-darwin.tar.gz"
  name "Meetless CLI"
  desc "Change-governance CLI (mla) for product delivery"
  homepage "https://meetless.ai"

  depends_on arch: :arm64

  binary "mla"

  caveats <<~CAVEATS
    The mla command is now on your PATH via Homebrew.
    Get started:  mla --help
  CAVEATS
end
